# Generated by Django 2.1.2 on 2018-10-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20181031_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='columns_json',
        ),
        migrations.RemoveField(
            model_name='query',
            name='rows_json',
        ),
        migrations.AddField(
            model_name='query',
            name='columns_pickle',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='rows_pickle',
            field=models.BinaryField(null=True),
        ),
    ]
