# Generated by Django 2.1.2 on 2018-10-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='duration_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
