# Generated by Django 2.1.2 on 2018-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_query_duration_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=250)),
                ('table_description', models.CharField(max_length=250)),
                ('table_description2', models.CharField(max_length=250)),
                ('column_name', models.CharField(max_length=250)),
                ('column_description', models.CharField(max_length=250)),
                ('column_description2', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
