# Generated by Django 2.1.2 on 2018-11-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ref',
            name='is_listed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
