# Generated by Django 2.1.2 on 2018-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remotetable_num_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotetable',
            name='num_rows_last',
            field=models.IntegerField(default=0),
        ),
    ]
