# Generated by Django 2.1.2 on 2018-12-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_remotetable_is_declared'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotetable',
            name='declared_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
